name: Postman Test

on:
  push:
    branches:
      - master

jobs:
  newman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-version: 6.0
          mongodb-username: root
          mongodb-password: secret
          mongodb-db: twitter

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.3

      - name: Install dependencies
        run: go get .

      - name: Build
        run: go build -o ./build/main .

      - name: Run API Server
        run: ./build/main &
        env:
          MONGOURI: mongodb://root:secret@localhost:27017/
          SECRET_KEY: abc&1*~#^2^#s0^=)^^7%b15

      - name: Run tests
        uses: matt-ball/newman-action@master
        with:
          collection: tests/go_twitter.postman_collection.json
          environment: tests/go_twitter.postman_environment.json
